export enum StudyPeriod {
  WITHIN_A_WEEK = "WITHIN_A_WEEK",
  WITHIN_A_MONTH = "WITHIN_A_MONTH",
  OVER_A_MONTH = "OVER_A_MONTH",
  SIX_MONTHS = "6MONTHS",
  WITHIN_A_YEAR = "WITHIN_A_YEAR",
  INCOMPLETE = "INCOMPLETE",
}
